"""empty message

Revision ID: 808117095275
Revises: 8547b9775f51
Create Date: 2020-08-01 14:23:08.281454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808117095275'
down_revision = '8547b9775f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
